spring:
  datasource:
    url: jdbc:mysql://localhost:3306/klab?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: vdongv1620
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update

decorator:
  datasource:
    p6spy:
      enable-logging: true

logging:
  level:
    org.hibernate.SQL: debug

